name: Check compilation and tests of Spoon

on: [push, workflow_dispatch]
  
jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Erlang
        run: sudo apt-get install erlang wget rebar -y

      - name: Get dependencies
        run: rebar3 get-deps

      - name: Compile 
        run: rebar3 compile

      - name: Test
        run: rebar3 eunit